export const COMMUNITY_LINKS = [
  {
    href: "https://chat.whatsapp.com/GlXCVD0zFAp9I0x67pt9vn",
    iconClass: "whatsapp",
    color: "primary",
    darkColor: "primaryDark",
  },
  {
    href: "https://t.me/dsccmrit",
    iconClass: "telegram",
    color: "telegram",
    darkColor: "telegramDark",
  },
  // {
  //   href: "https://discord.gg/2pCRQNNTq5",
  //   iconClass: "discord",
  //   color: "discord",
  //   darkColor: "discordDark",
  // },
  {
    href: "https://www.youtube.com/channel/UCnCH0DQtccx_7McXqaA_x6w",
    iconClass: "youtube",
    color: "youtube",
    darkColor: "youtubeDark",
  },
  {
    href: "https://www.linkedin.com/company/google-developer-student-club-cmrit/",
    iconClass: "linkedin",
    color: "linkedin",
    darkColor: "linkedinDark",
  },
];

export const TEAM_LINKS = [
  {
    Image: "/Members Images/Amartya.jpeg",
    Name: "Amartya Nambiar",
    Desg: "GDSC Lead",
    Interests: "Data science",
    Github: "https://github.com/amartyanambiar",
    LinkedIn: "https://www.linkedin.com/in/amartya-nambiar1/",
    Instagram: "",
  },
  {
    Image: "/Members Images/Arpan.png",
    Name: "Arpan Abhishek",
    Desg: "Tech Lead",
    Interests: "Web development and blockchain",
    Github: "https://github.com/arpancodes",
    LinkedIn: "https://www.linkedin.com/in/arpancodes/",
    Instagram: "https://www.instagram.com/arpancodes/",
  },
  {
    Image: "/Members Images/Gargi.jpeg",
    Name: "Gargi Sharma",
    Desg: "Marketing Lead",
    Interests: "",
    Github: "https://github.com/",
    LinkedIn: "https://www.linkedin.com/in/",
    Instagram: "",
  },
  {
    Image: "/Members Images/Amrutha.png",
    Name: "C K Amrutha",
    Desg: "Core Member",
    Interests: "Aspiring web developer",
    Github: "https://github.com/Amrutha1101",
    LinkedIn: "https://www.linkedin.com/in/amrutha-c-k-77a206196/",
    Instagram: "https://www.instagram.com/ck._.amrutha/",
  },
  {
    Image: "/Members Images/Rajneesh.jpeg",
    Name: "Rajneesh Khare",
    Desg: "Core Member",
    Interests: "RPA, Django",
    Github: "https://github.com/rajneeshk94",
    LinkedIn: " https://www.linkedin.com/in/rajneesh-khare-555a881b4/",
    Instagram: " https://www.instagram.com/__.r.a.j.__/",
  },
  {
    Image: "/Members Images/Satwik.png",
    Name: "Kumar Satwik",
    Desg: "Core Member",
    Interests: "Aspiring android developer",
    Github: "https://github.com/developer-metalhead",
    LinkedIn: "https://www.linkedin.com/in/kumar-satwik-038291203/",
    Instagram: "https://www.instagram.com/developer_metalhead/",
  },
  {
    Image: "/Members Images/Ayush.png",
    Name: "Aayush Dubey",
    Desg: "Core Member",
    Interests: "Competitive programming",
    Github: "",
    LinkedIn: "http://linkedin.com/in/aayush-dubey-05159b218",
    Instagram: "",
  },
  {
    Image: "/Members Images/Sayan.png",
    Name: "Sayan Basu",
    Desg: "Core Member",
    Interests: "Artificial Intelligence and Machine Learning",
    Github: "https://github.com/sayanbasu-cs",
    LinkedIn: "https://www.linkedin.com/in/sayan-basu-174985201/",
    Instagram: "https://www.instagram.com/sayanbasu.py/",
  },
  {
    Image: "/Members Images/Babitha.jpeg",
    Name: "Babitha Kumari",
    Desg: "Core Member",
    Interests: "Has sound knowledge in web development",
    Github: "https://github.com/Babithakumari",
    LinkedIn: "https://www.linkedin.com/in/babithakumari/ ",
    Instagram: "https://www.instagram.com/bub_._ly/",
  },
  {
    Image: "/Members Images/Rijuth.jpeg",
    Name: "Rijuth Menon R",
    Desg: "Core Member",
    Interests: "Full stack Development, Blockchain and FOSS",
    Github: "https://github.com/markisdev",
    LinkedIn: " https://linkedin.com/in/rijuthmenon",
    Instagram: "https://instagram.com/rijuth",
  },
];
